--
-- 表的结构 `program`
--

CREATE TABLE IF NOT EXISTS `program` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT,
  `resource` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '资源',
  `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '栏目名',
  `insert_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_resource` (`resource`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='栏目';

--
-- 表的结构 `news`
--

CREATE TABLE IF NOT EXISTS `news` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT,
  `url` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '原始url',
  `title` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '标题',
  `desc` TEXT NOT NULL COMMENT '简述',
  `pub_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '发布时间',
  `source` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '来源',
  `content` TEXT NOT NULL COMMENT '内容',
  `program` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '栏目ID',
  `insert_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='新闻内容';